#!/usr/bin/python3
# lab12_example5.py
# send email from Python script using IMAP
# to GMail account
# Note must change security level of gmail account to "less secure"
# https://www.google.com/settings/security/lesssecureapps

import imaplib
import email.utils
import time
from email.message import Message
import getpass

to_email = 'eilidhsouthren@gmail.com'
servername = 'imap.gmail.com'
serverport = '993'
username = 'eilidhsouthren@gmail.com'
from_sender_name = 'Eilidh S'
from_sender_email = '1513195@rgu.ac.uk'
body = '''Test message from raspberry pi,
generated by Python script'''
subject = 'Test message from Pi by Python'

# there is a bug with IDLE3
# if script makes call to getpass() when launched
# from IDLE3 the script will fail
# call to getpass works cleanly when script is executed
# from a console window
password = 'jabber_wocky'
# uncomment next line if you insist on running from IDLE3
# but beware your password will echo in clear text
# password = input('password for '+username+': ')

# Create the message
msg = Message()
msg['To'] = email.utils.formataddr(('Recipient', to_email))
msg['From'] = email.utils.formataddr((from_sender_name, from_sender_email))
msg['Subject'] = subject
#msg['Date'] = email.utils.formatdate(localtime = 1)
msg['Message-ID'] = email.utils.make_msgid()
msg.set_payload(body)

conn = imaplib.IMAP4_SSL(servername, serverport)

try:
    conn.login(username, password)    
    conn.append('INBOX','',imaplib.Time2Internaldate(time.time()), str(msg).encode())
finally:
    try:
        conn.close()
    except:
        pass
conn.logout()
